dev branch init push
jetseoo/forecast pull request #1
Opened 2022-11-22 10:11 UTC by jetseoo

2022-11-22 11:12 UTC, kingheskey commented on src/App.js
> +      const data = await (await fetch(getFetchUrl(adress))).json();
Для читабельности лучше делить такие операции на несколько

2022-11-22 11:13 UTC, kingheskey commented on src/App.js
> +        <React.Fragment>
Вместо <React.Fragment> </React.Fragment> можно писать <></>

2022-11-22 11:14 UTC, kingheskey commented on src/App.js
> +            <Today data={data}></Today>
Вместо того, чтобы явно пробрасывать data в компоненты-потомки, лучше сделать контекст и забирать эти данные через контекст. Это удобнее чем везде передавать пропсы

2022-11-22 11:15 UTC, kingheskey commented on src/App.js
> +  useEffect(() => {
Слой работы с данными лучше перенести в другое место. Например в отдельный хук useData, в котором будет стейт с данными и fetch. Если все это поместить в контекст (см. ниже) то вообще красиво будет

2022-11-22 11:59 UTC, kingheskey commented
Картинки пожми!!!! В идеале должны быть меньше 100кб, у тебя есть на мегабайт

2022-11-24 15:54 UTC, jetseoo commented on src/Components/Header.js
> +        <input
Сделать для провайдера отдельный компонент, который будет внутри себя вызывать **data**  и его поместить на самом верхнем уровне в индекс (оберуть Апп) 

Избавиться от стейта newCity - дублируется. Убрать реф, сделать компонент контролируемым

2022-11-24 15:55 UTC, jetseoo commented on src/Components/Tomorrow.js
> +          {Math.round(tomorrow.temp)}
Паттерн adapter

2022-12-12 16:49 UTC, kingheskey commented on src/API.js
> +  if (!location) location = 'Batumi';
Для такого есть специальный синтаксис: export const getFetchUrl = (location = 'Batumi') => ...

2022-12-12 16:49 UTC, kingheskey commented on src/API.js
> +export const convertWindDir = (deg) => {
Это будет выглядеть лучше, если сделать switch-case
switch (true): 
    case (deg <= 22.5) {
         return 'N;
    case (deg <= 67.5) {
         return 'NE';
....

2022-12-12 16:49 UTC, kingheskey commented on src/App.js
> +import './App.css';
Собери эти CSS импорты в один файл и импортируй его.
У тебя будет CSS index.css (например), в котором просто будет импорт двух CSS файлов

 Обычно еще импорт CSS пишут под импортом JS

2022-12-12 16:49 UTC, kingheskey commented on src/App.css
> +* {
На будущее можешь почитать про БЭМ (популярная конвенция нейминга HTML-элементов) и про то, как правильно организовывать CSS в проекте

2022-12-12 17:59 UTC, kingheskey reviewed
Компоненты и соответствующие css файлы раскидай по папочкам, бардак небольшой в папке Components

2022-12-12 17:59 UTC, kingheskey commented on src/Components/DetailsCard.js
> +const DetailsCard = ({ heading, blockId }) => {
Домашка: почитать про React-prop-types
Когда дочитаешь: обычно вместе с типами пропсов указывают, для чего нужен тот или иной пропс. Тут например не совсем понятно, что делает blockId, как раз неплохо было бы добавить в коде комментарий на этот счет

2022-12-12 17:59 UTC, kingheskey commented on src/Components/DetailsCard.js
> +        return pairs.map((pair) => {
Это можно делать сразу: pairs.map(([prop, name]) => ...

2022-12-12 17:59 UTC, kingheskey commented on src/Components/Today.js
> +        <p className="sunrise">{today.sunrise.slice(0, 5)}</p>
Это тоже в контекст вместе с округлениями. Создай функцию, где ты будешь принимать ответ из апи как параметр, и возвращать только нужные тебе поля в нужном тебе виде. Это вот то, что было про паттерн Адаптер

2022-12-12 17:59 UTC, kingheskey commented on src/index.css
> +  font-family: 'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
Уверен что у тебя столько шрифтов в браузере есть? Импортируется только Montserrat, остальные не факт что есть у пользователя. Оставь монтсеррат и sans-serif

2022-12-15 12:12 UTC, jetseoo commented on src/Components/Today.js
> +        <p className="sunrise">{today.sunrise.slice(0, 5)}</p>
Время приходит просто как string 00:11:22

2022-12-30 07:55 UTC, kingheskey requested changes
В целом норм

2022-12-30 07:55 UTC, kingheskey commented on src/App.js
> +import Header from './Components/header/Header.js';
Это необязательно, но можно сделать вот что:

В каждую папку с компонентами кладешь файл index.js
В нем делаешь export * from './Header.js'

В этом файле меняешь './Components/header/Header.js'; на  './Components/header';
https://stackoverflow.com/questions/60458904/why-do-i-have-to-create-index-js-file-for-components тут подробнее зачем это

2022-12-30 07:55 UTC, kingheskey commented on src/App.js
> +import Week from './Components/week/week.js';
JS импорты над CSS

2022-12-30 07:55 UTC, kingheskey commented on src/Components/UI/Card.css
> +  background-color: #2c2d2f;
На будущее - изначально создаешь файл с CSS переменными. Создаешь переменные с повторяющимися значениями - например основные цвета, паддинги и маржины которые повторяются в проекте и.т.д. Потом когда нужно поменять какой то цвет по всему проекту - ты просто меняешь переменную, а не гоняешь по всем файлам

2022-12-30 07:55 UTC, kingheskey commented on src/Components/details/DetailsCard.js
> -      <h3 className="details-heading semi-bold">{heading}</h3>
Ну раньше лучше было. Зачем удалил

2022-12-30 07:55 UTC, kingheskey commented on src/Components/week/week.css
> +  height: -webkit-fill-available;
Это не будет работать на фаерфоксе. Префикс -webkit для браузеров на хромиуме и на чем там сафари. Фаерфокс на другом ядре, так что CSS парсер на фаерфоксе проигнорирует то, что ты написал

https://stackoverflow.com/questions/26275982/putting-moz-available-and-webkit-fill-available-in-one-width-css-property

2022-12-30 07:55 UTC, kingheskey commented on src/Components/week/week.js
> +      weekday: date.toLocaleDateString('en-US', { weekday: 'short' }),
Преобразование можно тоже запихнуть в контекст и брать все оттуда. Лучше не размазывать логику по компоненту если это возможно

2022-12-30 07:55 UTC, kingheskey commented on src/hooks/useData.js
> +    resultData.days = data.days.map((day) => {
Сколько дней в массиве days? Если больше двух недель то это уже многовато и обрежь лишние
В идеале вообще посмотреть АПИ, может лишние дни можно вообще не запрашивать с сервера, чтобы не увеличивать размер тела ответа с сервера

2022-12-30 19:50 UTC, jetseoo commented on src/Components/details/DetailsCard.js
> -      <h3 className="details-heading semi-bold">{heading}</h3>
Заметил, что вместо того, чтобы в нескольких местах в этот h3 прописывать класс semi-bold, я могу в одном месте в details-heading прописать fw600 и будет работать также. Изначально создавал этот класс с мыслью о том, что много где пригодится, но на самом деле нет

2023-01-04 07:14 UTC, kingheskey approved these changes

2023-01-04 07:14 UTC, kingheskey commented on src/hooks/useData.js
> +      console.log(newData);
консоль лог

2023-01-04 13:29 UTC, merged